### ISSUE TITLE
Google Maps not loaded in many tests

### ISSUE THREAD

**Issue by hampelm** [postcode/senoia#139]
Looks like Google Maps isn't getting loaded. Might be an async problem, and or something deeper. In any case, we should fix or decide to ignore the error. 

```
  10) Medical Provider Confirmation Mecidal Provider Contact when a medical asset is added to a plan gets a confirmation email
      Failure/Error: within '.first_aid_station_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/1:510
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/provider_confirmation_spec.rb:25:in `block (4 levels) in <top (required)>'

  11) Medical Provider Confirmation Mecidal Provider Contact when a medical asset is added to a plan when clicking yes on the confirmation email they are asked to log in
      Failure/Error: within '.first_aid_station_name' do'

... etc etc
```

**Comment by hampelm** [comment]
Similar errors in a couple other specs:

```
  44) Plan viewing an existing plan admin can add a transport
      Failure/Error: within '.transport_id_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/1:721
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/plans_spec.rb:152:in `block (3 levels) in <top (required)>'

  45) Plan viewing an existing plan admin can add a mobile team
      Failure/Error: within '.mobile_teams_id_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/1:645
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/plans_spec.rb:139:in `block (3 levels) in <top (required)>'

  46) Plan viewing an existing plan admin can add a first aid station
      Failure/Error: within '.first_aid_station_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/1:558
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/plans_spec.rb:124:in `block (3 levels) in <top (required)>'

  47) Plan viewing an existing plan admin can add a dispatch
      Failure/Error: within '.dispatch_id_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/1:793
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/plans_spec.rb:111:in `block (3 levels) in <top (required)>'

  48) Plan when there are two operation periods admin can add a first aid station to the second
      Failure/Error: within '.first_aid_station_name' do

      Capybara::Poltergeist::JavascriptError:
        One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

        ReferenceError: Can't find variable: google
        ReferenceError: Can't find variable: google
            at http://127.0.0.1:56184/assets/application.js:40134 in map_initialize
            at http://127.0.0.1:56184/plans/2:504
            at http://127.0.0.1:56184/assets/application.js:4671 in dispatch
            at http://127.0.0.1:56184/assets/application.js:4339 in handle
            at http://127.0.0.1:56184/assets/application.js:4580 in trigger
            at http://127.0.0.1:56184/assets/application.js:5290
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:5289 in trigger
            at http://127.0.0.1:56184/assets/application.js:34120
            at :0
            at http://127.0.0.1:56184/assets/application.js:7475 in complete
            at http://127.0.0.1:56184/assets/application.js:3149 in fire
            at http://127.0.0.1:56184/assets/application.js:3195 in add
            at http://127.0.0.1:56184/assets/application.js:7420 in Animation
            at http://127.0.0.1:56184/assets/application.js:7500 in doAnimation
            at http://127.0.0.1:56184/assets/application.js:4034 in dequeue
            at http://127.0.0.1:56184/assets/application.js:4077
            at http://127.0.0.1:56184/assets/application.js:385 in each
            at http://127.0.0.1:56184/assets/application.js:137 in each
            at http://127.0.0.1:56184/assets/application.js:4070 in queue
            at http://127.0.0.1:56184/assets/application.js:7511 in animate
            at http://127.0.0.1:56184/assets/application.js:34118
            at :0
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:287:in `within'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/plans_spec.rb:284:in `block (3 levels) in <top (required)>'

  49) Collaborators Admin adds a collaborator
      Failure/Error: find("#plan_view_id_#{@user.id}").set(true)

      Capybara::ElementNotFound:
        Unable to find css "#plan_view_id_2"
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:43:in `block in find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
      # /Users/matth/.rvm/gems/ruby-2.2.0-preview1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      # ./spec/acceptance/collaborators_spec.rb:22:in `block (3 levels) in <top (required)>'
```

**Comment by hampelm** [comment]
Took a while to figure out the incantations to actually see the requests being made. Here's the code I used to debug: 

```
        page.driver.network_traffic.each do |request|
          request.response_parts.uniq(&:url).each do |response|
            puts "#{response.url}: #{response.status}"
          end
        end
```
